version: "2"

services:
  # https://docs.docker.com/docker-hub/builds/automated-testing/
  sut:
    build:
      context: ./test
      dockerfile: Dockerfile
    depends_on:
      - jenkins
    volumes_from:
      - jenkins
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  jenkins:
    # For development or CI, tag build from local Dockerfile
    build:
      context: ./
      dockerfile: Dockerfile
      args: 
        - TAG=${TAG}
        - VCS_REF=${VCS_REF}
        - BUILD_DATE=${BUILD_DATE}
    # For production, download prebuilt image
    image: ${IMAGE_NAME}
    container_name: jenkins
    hostname: jenkins
    #restart: always
    #group_add: 
    #  - docker
    ports:
      - '8081:8080'
      - '8443:8443'
      - '50000:50000'
    environment:
      ## Jenkins Config
      - JENKINS_USERNAME=${JENKINS_ADMIN_LOGIN}
      - JENKINS_PASSWORD=${JENKINS_ADMIN_PWD}
    volumes:
      - /srv/jenkins/bitnami:/bitnami
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
